### ISSUE TITLE
Raspberry Pi 4

### ISSUE THREAD

**Issue by jrraines** [adafruit/Pi_Eyes#14]
When I try to run this on a Pi4 I get:

> pi@rpi4:/boot/Pi_Eyes $ python cyclops.py
Traceback (most recent call last):
  File "cyclops.py", line 100, in <module>
    DISPLAY = pi3d.Display.create(samples=4)
  File "/home/pi/.local/lib/python2.7/site-packages/pi3d/Display.py", line 560, in create
    display.opengl.create_display(x, y, w, h, depth=depth, samples=samples, layer=layer, display_config=display_config, window_title=window_title)
  File "/home/pi/.local/lib/python2.7/site-packages/pi3d/util/DisplayOpenGL.py", line 93, in create_display
    assert self.context != EGL_NO_CONTEXT and self.context is not None
AssertionError<

I have done apt-get install libgles2-mesa-dev, hoping that would resolve the issue. I suspect it has something to do with the Pi4's dual display capability.

**Comment by ladyada** [comment]
https://learn.adafruit.com/animated-snake-eyes-bonnet-for-raspberry-pi/raspberry-pi-4-experimental
